### ISSUE TITLE
Explaination

### ISSUE THREAD

**Issue by abdulsami34** [huytc/gameworld-csgo#1]
Can you please possibly explain this system to me in easy words? Can i use this for a simple matchmaking 3rd party service?

**Comment by huytc** [comment]
Well I'm trying to create a web platform where you can create a team and challenge other teams to advance on the ladder. But I have only begun working on this and haven't got anything done really, so I'm afraid it wouldn't be able to help you.

**Comment by abdulsami34** [comment]
Any alternative you could suggest or any advice.

**Comment by huytc** [comment]
Can you tell me more about what you want and I'll see if I can help.

**Comment by abdulsami34** [comment]
I want a lobby matchmaking. People queue and play. Just this. Or a simple scrim like popflash.

**Comment by huytc** [comment]
So have you tried FaceIT or Sostronk

**Comment by abdulsami34** [comment]
Yes. But i want to open my own.

**Comment by huytc** [comment]
To host your own server, you can follow Valve’s guide here:
https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Dedicated_Servers.
But if you want a system like FaceIT I don’t think there is any open-source
one.

**Comment by abdulsami34** [comment]
I have servers.
I want a simple system like popflash. Is that possible if you could help me with?

**Comment by huytc** [comment]
I'm not sure about that as I'm quite busy right now. For further discussion please contact me through my email tc.huy.7@gmail.com
I'll close the issue here.
